import type { Metadata } from "next";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import {NuqsAdapter} from "nuqs/adapters/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"
import TerraLysAIAssistant from "@/components/terralys-ai-assistant"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
      <TRPCReactProvider>
        <html lang="en">
          <body
          >
            <Toaster position="top-right" richColors/>
            {children}
            {/* Assistant TerraLys AI - Accessible sur toutes les pages */}
            <TerraLysAIAssistant />
             <SpeedInsights/>
             <Analytics/>
          </body>
        </html>
      </TRPCReactProvider>
    </NuqsAdapter>
  );
}
